### ISSUE TITLE
KeyError: 'token'

### ISSUE THREAD

**Issue by kcobos** [sclukey/rmate-python#1]
Hi, 
when Atom is closing the file, I get this error message:

Traceback (most recent call last):
  File "/usr/bin/rmate", line 302, in <module>
    main()
  File "/usr/bin/rmate", line 298, in main
    handle_cmds(s, settings.host, settings.port, cmds)
  File "/usr/bin/rmate", line 124, in handle_cmds
    handle_cmd(textmate, dec(command).strip())
  File "/usr/bin/rmate", line 86, in handle_cmd
    elif cmd == 'close': handle_close(textmate, variables, data)
  File "/usr/bin/rmate", line 61, in handle_close
    path = variables['token']
KeyError: 'token'

**Comment by sclukey** [comment]
I assume that you are using [remote-atom](https://atom.io/packages/remote-atom)? If so then this issue is because the server [does not send the token](https://github.com/randy3k/remote-atom/blob/efdd7eff85a14dd4b4a47595959c9e4bc2872290/lib/remote-atom.coffee#L142-L148) when it closes a file [like it is supposed to](https://github.com/textmate/textmate/blob/30b409b2eb7fafc1aceec81d14a4404bcb0aca7c/Applications/TextMate/src/RMateServer.mm#L326). It really should send the token, but for the sake of robustness 251cbe5 should fix this issue. Reopen this if not.

Thanks
